### ISSUE TITLE
No Serial Port Selector 

### ISSUE THREAD

**Issue by DIYElectronicsZA** [DIYElectronicsZA/PSU.T-Power_Supply_Unicorn_Tamer-#1]
App needs to start with the serial port closed, then display a list of the available ports. 
The port must be selected by the user and then connected manually somehow (button?) 

Opening the port needs to be able to catch errors with a try - catch structure or similar.

Port must be closed when close / disconnect / app closed button 

Also needs to deal gracefully with accidental disconnection

**Comment by DIYElectronicsZA** [comment]
@CiciDIY  See https://github.com/pyserial/pyserial/blob/master/examples/wxSerialConfigDialog.py

**Comment by ramb0t** [comment]
@CiciDIY This is fixed now?
