### ISSUE TITLE
Error counter

### ISSUE THREAD

**Issue by ramb0t** [DIYElectronicsZA/PSU.T-Power_Supply_Unicorn_Tamer-#5]
Create an error counter variable for each channel 
When a reading goes outside of the min / max bounds, increase this error variable. Display the current error count on the UI. 

Next add a max error count limit input, perhaps set to 10 errors initially (but user changeable) , and a PASS / FAIL (maybe in green / red) indicator on the UI 
If the error count exceeds the max, then display FAIL 

Later we will add a timer and if the test runs without errors for the allocated test time, then PASS will be displayed

**Comment by CiciDIY** [comment]
I have done this thing!
